<?php

namespace Database\Seeders;

use App\Models\Employee;
use Illuminate\Database\Seeder;

class EmployeeSeeder extends Seeder
{
    public function run(): void
    {
        $employees = [
            [
                'id' => 1,
                'employee_id' => 'EMP-0001',
                'first_name' => 'Mariale Princess',
                'middle_name' => 'C.',
                'last_name' => 'Unabia',
                'suffix' => null,
                'date_of_birth' => null,
                'sex' => 'Female',
                'civil_status' => 'Married',
                'email' => null,
                'mobile_number' => null,
                'address' => null,
                'department_id' => 2,
                'position_id' => 4,
                'employment_type_id' => 1,
                'date_hired' => null,
                'date_regularized' => null,
                'employment_status' => 'Active',
                'basic_salary' => 35858.47,
                'pay_frequency' => 'Semi-Monthly',
                'payroll_enabled' => true,
            ],

            [
                'id' => 2,
                'employee_id' => 'EMP-0002',
                'first_name' => 'Marsha',
                'middle_name' => null,
                'last_name' => 'Moreno',
                'suffix' => null,
                'date_of_birth' => null,
                'sex' => 'Female',
                'civil_status' => 'Single',
                'email' => null,
                'mobile_number' => null,
                'address' => null,
                'department_id' => 2,
                'position_id' => 7,
                'employment_type_id' => 1,
                'date_hired' => null,
                'date_regularized' => null,
                'employment_status' => 'Active',
                'basic_salary' => 31311.32,
                'pay_frequency' => 'Semi-Monthly',
                'payroll_enabled' => true,
            ],

            [
                'id' => 3,
                'employee_id' => 'EMP-0003',
                'first_name' => 'Abigail',
                'middle_name' => null,
                'last_name' => 'Alto',
                'suffix' => null,
                'date_of_birth' => null,
                'sex' => 'Female',
                'civil_status' => 'Married',
                'email' => null,
                'mobile_number' => null,
                'address' => null,
                'department_id' => 2,
                'position_id' => 6,
                'employment_type_id' => 1,
                'date_hired' => null,
                'date_regularized' => null,
                'employment_status' => 'Active',
                'basic_salary' => 20604.83,
                'pay_frequency' => 'Semi-Monthly',
                'payroll_enabled' => true,
            ],

            [
                'id' => 4,
                'employee_id' => 'EMP-0004',
                'first_name' => 'Christine',
                'middle_name' => 'H.',
                'last_name' => 'Catalla',
                'suffix' => null,
                'date_of_birth' => null,
                'sex' => 'Female',
                'civil_status' => 'Single',
                'email' => null,
                'mobile_number' => null,
                'address' => null,
                'department_id' => 2,
                'position_id' => 5,
                'employment_type_id' => 1,
                'date_hired' => null,
                'date_regularized' => null,
                'employment_status' => 'Active',
                'basic_salary' => 21897.44,
                'pay_frequency' => 'Semi-Monthly',
                'payroll_enabled' => true,
            ],

            [
                'id' => 5,
                'employee_id' => 'EMP-0005',
                'first_name' => 'Abe',
                'middle_name' => null,
                'last_name' => 'Gabrillo',
                'suffix' => null,
                'date_of_birth' => null,
                'sex' => 'Male',
                'civil_status' => 'Single',
                'email' => null,
                'mobile_number' => null,
                'address' => null,
                'department_id' => 3,
                'position_id' => 8,
                'employment_type_id' => 1,
                'date_hired' => null,
                'date_regularized' => null,
                'employment_status' => 'Active',
                'basic_salary' => 25624.40,
                'pay_frequency' => 'Semi-Monthly',
                'payroll_enabled' => true,
            ],

            [
                'id' => 6,
                'employee_id' => 'EMP-0006',
                'first_name' => 'Paul Cedrick',
                'middle_name' => 'Manalaysay',
                'last_name' => 'Reyes',
                'suffix' => null,
                'date_of_birth' => '2000-09-09',
                'sex' => 'Male',
                'civil_status' => 'Single',
                'email' => 'pcreyes09@gmail.com',
                'mobile_number' => '09214048218',
                'address' => 'Malolos, Bulacan',
                'department_id' => 1,
                'position_id' => 1,
                'employment_type_id' => 1,
                'date_hired' => '2024-01-04',
                'date_regularized' => '2024-04-04',
                'employment_status' => 'Active',
                'basic_salary' => 26000.00,
                'pay_frequency' => 'Semi-Monthly',
                'payroll_enabled' => true,
            ],

            [
                'id' => 10,
                'employee_id' => 'EMP-2026-0010',
                'first_name' => 'Christian Neil',
                'middle_name' => null,
                'last_name' => 'Vacaro',
                'suffix' => null,
                'date_of_birth' => null,
                'sex' => 'Male',
                'civil_status' => 'Single',
                'email' => null,
                'mobile_number' => null,
                'address' => null,
                'department_id' => 1,
                'position_id' => 3,
                'employment_type_id' => 2,
                'date_hired' => null,
                'date_regularized' => null,
                'employment_status' => 'Active',
                'basic_salary' => 18000.00,
                'pay_frequency' => 'Semi-Monthly',
                'payroll_enabled' => true,
            ],

            [
                'id' => 11,
                'employee_id' => 'EMP-2026-0011',
                'first_name' => 'Christopher Lance',
                'middle_name' => 'P.',
                'last_name' => 'Orendain',
                'suffix' => null,
                'date_of_birth' => null,
                'sex' => 'Male',
                'civil_status' => 'Single',
                'email' => null,
                'mobile_number' => null,
                'address' => null,
                'department_id' => 1,
                'position_id' => 2,
                'employment_type_id' => 2,
                'date_hired' => null,
                'date_regularized' => null,
                'employment_status' => 'Active',
                'basic_salary' => 18000.00,
                'pay_frequency' => 'Semi-Monthly',
                'payroll_enabled' => true,
            ],
        ];

        foreach ($employees as $data) {
            $id = $data['id'];

            Employee::updateOrCreate(
                ['id' => $id],
                $data
            );
        }

        $this->command?->info(
            'Imported ' . count($employees) . ' employees.'
        );
    }
}
